# 问卷星配置文件 (由此脚本自动生成或手动编辑)

config_data = {'questionnaire_url': 'https://www.wjx.cn/vm/hAjx6yG.aspx#',
               'number_of_submissions': 40,
               'mobile_user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) '
                                    'Chrome/138.0.0.0 Safari/537.36',
               'min_delay_seconds': 70.0,
               'max_delay_seconds': 180.0,
               'questions': [{'id': '1',
                              'description': '性别',
                              'type': 'single_choice_random_int',
                              'answer_logic': {'min': 1, 'max': 2}},
                             {'id': '2',
                              'description': '年级',
                              'type': 'single_choice_random_int',
                              'answer_logic': {'min': 1, 'max': 4}},
                             {'id': '3',
                              'description': '平均月消费',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 4, 'probabilities': [0.25, 0.25, 0.1, 0.4]}},
                             {'id': '4',
                              'description': '生活费来源',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 3, 'probabilities': [0.0, 0.6, 0.4]}},
                             {'id': '5',
                              'description': '校内就餐费用',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 4, 'probabilities': [0.3, 0.4, 0.2, 0.1]}},
                             {'id': '6',
                              'description': '零食校外饮食费用',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 4, 'probabilities': [0.1, 0.5, 0.3, 0.1]}},
                             {'id': '7',
                              'description': '购物方式',
                              'type': 'single_choice_random_int',
                              'answer_logic': {'min': 1, 'max': 2}},
                             {'id': '8',
                              'description': '衣服',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 4, 'probabilities': [0.1, 0.5, 0.3, 0.1]}},
                             {'id': '9',
                              'description': '化妆品',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 5, 'probabilities': [0.1, 0.3, 0.2, 0.3, 0.1]}},
                             {'id': '10',
                              'description': '双11',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 5, 'probabilities': [0.1, 0.3, 0.2, 0.3, 0.1]}},
                             {'id': '11',
                              'description': '朋友聚餐',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 3, 'probabilities': [0.2, 0.5, 0.3]}},
                             {'id': '12',
                              'description': '父母',
                              'is_conditional': True,
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 2, 'probabilities': [0.6, 0.4]}},
                             {'id': '13',
                              'description': '是否奢侈品',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 2, 'probabilities': [0.6, 0.4]}},
                             {'id': '14',
                              'description': '学习资料，课外读物',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 4, 'probabilities': [0.1, 0.5, 0.3, 0.1]}},
                             {'id': '15',
                              'description': '生活费感觉',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 3, 'probabilities': [0.6, 0.3, 0.1]}},
                             {'id': '16',
                              'description': '恋爱',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 4, 'probabilities': [0.1, 0.5, 0.3, 0.1]}},
                             {'id': '17',
                              'description': '直播打赏金额',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 4, 'probabilities': [0.1, 0.5, 0.3, 0.1]}},
                             {'id': '18',
                              'description': '消费方面',
                              'type': 'Multiple_choices_probabilities',
                              'answer_logic': {'options_count': 7,
                                               'probabilities': [0.1, 0.5, 0.3, 0.1, 0.6, 0.3, 0.4]}},
                             {'id': '19',
                              'description': '花钱方式',
                              'type': 'single_choice_probabilities',
                              'answer_logic': {'options_count': 5, 'probabilities': [0.1, 0.3, 0.2, 0.3, 0.1]}},
                             {'id': '20',
                              'description': '支付方式',
                              'type': 'Multiple_choices_probabilities',
                              'answer_logic': {'options_count': 5, 'probabilities': [0.0, 0.5, 0.1, 0.2, 0.8]}},
                             {'id': '21',
                              'description': '用处',
                              'type': 'Multiple_choices_probabilities',
                              'answer_logic': {'options_count': 6, 'probabilities': [0.6, 0.5, 0.3, 0.1, 0.6, 0.1]}}
                             ]}
